package miden:game-account@0.1.0;

use miden:base/core-types@1.0.0;

interface game-account {
    use core-types.{felt, word};

    // TODO: id should probably be a string
    register-player: func(commit: word);

    propose-team: func(players: list<word>);

    vote-team-proposal: func(commit: word, vote: felt);

}

world game-account-world {

    export game-account;
}
